Jenkins file update

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -8,36 +8,40 @@ pipeline {
     stages {
         stage('Checkout Code') {
             steps {
+                echo 'Checking out code...'
                 checkout scm
             }
         }
 
         stage('Install Dependencies') {
             steps {
-                bat '''
-                npm install -g vercel
-                composer install
-                npm install
-                npm run build
-                '''
+                echo 'Installing global tools and dependencies...'
+                bat 'npm install -g vercel'
+                bat 'composer install'
+                bat 'npm install'
+                bat 'npm run build'
             }
         }
 
         stage('Run Tests') {
             steps {
-                bat '''
-                php artisan test || exit /b 0
-                '''
+                echo 'Running Laravel tests...'
+                // This will log errors but not fail the pipeline
+                bat 'php artisan test || echo "Tests failed but continuing..."'
             }
         }
 
         stage('Deploy to Vercel') {
             steps {
-                bat '''
-                vercel --prod --token %VERCEL_TOKEN% --yes
-                '''
+                echo 'Deploying to Vercel...'
+                bat 'vercel --prod --token %VERCEL_TOKEN% --yes'
             }
         }
     }
+
+    post {
+        always {
+            echo 'Pipeline completed!'
+        }
+    }
 }
-            
